camp/urls.py
from django.conf import settings
from django.urls import path
from django.contrib import admin
from django.conf.urls import include

from . import views


if settings.DEBUG:
    import debug_toolbar

app_name='camp'
urlpatterns = [
    path('', views.create, name='create'),
    #camp registration
        #/new/
        #/new/confirm/
        #/new/edit/  <--- an alias to confirm
        #/new/save/
    path('create/', views.create, name='create'),
    path('create/<int:registration_id>', views.create, name='create_edit'),
    path('delete/camper/<int:registration_id>', views.deletecamper, name='deletecamper'),
    path('delete/registration/<int:registration_id>', views.delete_entire_registration, name='delete_entire_registration'),
    path('donaterebate/<int:registration_id>', views.donaterebate, name='donaterebate'),
    path('confirm/<int:registration_id>', views.confirm, name='confirm'),
    path('final/<int:registration_id>', views.final, name='final'),
    path('final/', views.final, name='final'),
    path('status/<int:registration_id>', views.status, name='status'),
    path('checkpayment/<int:registration_id>', views.checkpayment, name='check_payment'),
    path('paypalpayment/<int:registration_id>', views.paypalpayment, name='paypal_payment'),
    path('paypalreturn/<int:registration_id>', views.paypalreturn, name='paypal_return'),
    path('test/500', views.my500, name='test_500'),
    path('help/', views.help, name='help'),
    path('check_membership/', views.check_membership, name='check_membership'),
    path('help/<slug>', views.help, name='help_slug'),
    path("view", views.homepage, name="homepage"),
    path("test", views.test, name="test"),
    path("test/", views.test, name="test"),
]

membership/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import include

from . import views

admin.site.site_header = 'Database Admin Panel'
admin.site.site_title = 'Database Admin Panel'

app_name='membership'

urlpatterns = [
    path("", views.create, name="create"),
    path('<int:registration_id>', views.create, name='create_edit'),
    path('help/', views.help, name='help'),
    path("create/", views.create, name="create"),
    path('create/<int:registration_id>', views.create, name='create_edit')
]

registrar/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import include

from . import views

admin.site.site_header = 'Database Admin Panel'
admin.site.site_title = 'Database Admin Panel'


app_name='registrar'
urlpatterns = [
    path("", views.homepage, name="homepage"),
    path('reports', views.reports_home, name='reports_home'),
    path('docs', views.docs, name='docs'),
    path('payments', views.payments, name='payments'),
    path('payments/add', views.payments_add, name='payments_add'),
    path('payments/report', views.payments_report, name='payments_report'),
    path('payment/view/<int:payment_id>', views.payment_view, name='payment_view'),
    path('payment/ipn_view/<int:ipn_id>', views.ipn_view, name='ipn_view'),
    path('payments/delete/', views.payments_delete, name='payments_delete'),
    path('payments/delete/<int:payment_id>', views.payments_delete, name='payments_delete'),
    path('payments/edit/<int:payment_id>', views.payments_add, name='payments_add_edit'),
    path('payments/quick/<int:registration_id>', views.payments_quick, name='payments_quick'),
    path('registrar', views.registrar, name='registrar'),
    path('campconstants', views.campconstants, name='campconstants'),
    path('membership_report', views.membership_report, name='membership_report'),
    path('membership_report/<slug>', views.membership_report, name='membership_report'),
    path('registrar/update/<int:registration_id>', views.registrar_update, name='registrar_update'),
    path('adjustment/add', views.adjustment_add, name='adjustment_add'),
    path('approve/<int:registration_id>', views.approve, name='approve'),
    path('refund_report/', views.refund_report, name='refund_report'),
    path('refund/<int:registration_id>', views.refund, name='refund'),
    path('reports/<report_by_slug>', views.report_by_slug, name='reports_by_slug'),
    path('deposit', views.deposit, name='deposit'),
    path('donationletter/<int:registration_id>', views.donationletter_endpoint, name='donationletter'),
    path('view/<int:registration_id>', views.view, name='view'),
    path('renew', views.view, name='renew'),

]

tifddb/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

handler500 = 'camp.views.my500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include('camp.urls')),
    path('registrar/', include('registrar.urls')),
    path('membership/', include('membership.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('nested_admin/', include('nested_admin.urls')),
    re_path(r'^paypal_notify/', include('paypal.standard.ipn.urls')),


]

membership/models.py
from django.db import models
#from django.contrib.auth.models import AbstractUser
#from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm
from camp.models import *

registrar/models.py
from django.db import models
from django.forms import ModelForm
from camp.models import *
from camp.custom.mylogger import p

membership/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, reverse, redirect
from django.template import loader
from django.contrib import messages

from decimal import Decimal
import datetime

from registrar.views import renew_tifd_membership

from camp.views import generate_cart_from_registration
from camp.views import get_discount,  emailconfirmation, generate_email_html
from camp.views import create as campcreate
from camp.views import auth_check
from camp.models import *
from camp.custom.mylogger import p
from camp.custom.tday import tday

try:
    from camp.constants import dvd_price_decimal,membership_price_decimal
except: pass

from .forms import *
from .models import *

years = CampRegistration.objects.order_by('-year').values('year',).distinct()
now = datetime.datetime.now()


def create(request,registration_id=None):

    ###################  WARNING ##############################
    ##  membership:create and camp:create are MOSTLY the same.  
    #If you make a change here, it should probably be made in both places!
    ######################################################################
    save_success=False
    edit_view=False
    renewid=None
    registration_options=CampRegistrationTypes.objects.filter(active=True).filter(slug__exact="membership")

    if request.GET.get('renewid'):
        renewid=request.GET.get('renewid')
        renewid=int(renewid)
        p('RENEW:',(renewid),type(renewid))

    
    membership_valid_from,membership_valid_to=renew_tifd_membership(None,False)
    p("Example membership renewal facts begin/end",membership_valid_from,membership_valid_to)

    if registration_id:
        if auth_check(request,registration_id) is True:
             registration=CampRegistration.objects.get(pk=registration_id)
             edit_view=True
             registrationform = RegistrationFormset_edit(queryset=CampRegistration.objects.filter(pk=registration_id))
             p('Edit view access granted, regid:',registration_id)

        else:
            msg="Registration id "+str(registration_id) + " access denied "
            messages.add_message(request, 40, msg)
            #registration_id=None
            #registration=Registration()
            p ("Registration ID but not authenticated")
            return HttpResponseRedirect(reverse('camp:create'))
    else:
        registration_id=None
        registration=CampRegistration()
        registrationform = RegistrationFormset_new(queryset=CampRegistration.objects.filter(pk=registration_id))


    #regformform_person=PersonFormset(instance=registration,initial=[{'email': "blah"}])
    regformform_person=PersonFormset(instance=registration)

    #after we have built the forms, do the renewal stuff
    if (renewid) and (renewid > 0) and (auth_check(request,registration_id) is True):
        p("setting up the form from renew id ",renewid)
        old_registration=CampRegistration.objects.get(pk=renewid)
        registrationform = RegistrationFormset_new(queryset=CampRegistration.objects.filter(pk=registration_id))

        copy_fields=(
                'address1',
                'address2',
                'city',
                'state',
                'zip',
                'country',
                )
        for f in copy_fields:
            registrationform[0].fields[f].initial=getattr(old_registration, f)
        oldcampers=CampCamper.objects.filter(registration=renewid)

        copy_fields=(
                'first_name',
                'last_name',
                'phone',
                'email',
                )
        i=0
        for oldcamper in oldcampers:
            for f in copy_fields:
                a=getattr(oldcamper,f)
                p(f'setting form #{i} {f} -> {a}')
                regformform_person[0].fields[f].initial=getattr(oldcamper,f)
            i=i+1

        #for key,val in registrationform[0].fields.items():
        #    p(key,val)

    if request.method == 'POST':
        registrationform=RegistrationFormset_edit(request.POST,form_kwargs={'empty_permitted': True})
        regformform_person=PersonFormset(request.POST,instance=registration,form_kwargs={'empty_permitted': True})

        if regformform_person.has_changed():
            for form in regformform_person:
                if form.has_changed():
                    for c in form.changed_data:
                        p("[%s] adult form field %s went from \"%s\" to \"%s\"" % (str(registration.pk),c,form[c].initial, form[c].data))


        if ( registrationform.is_valid() and regformform_person.is_valid()):
            p ("DEBUG: all forms valid!\n")

            #check to see if either the base (address) form, of the first camper is empty.  If so, fail.
            #but DON'T fail if this is a user editing their existing form.
            if edit_view is False:
            #the following only detects *changes* so if you are editing and don't change anything it will fail
                if (registrationform[0].cleaned_data == {} or regformform_person[0].cleaned_data == {}):
                    p ("The first form of a formset should not be empty!")
                    if registrationform[0].cleaned_data == {}:
                        msg="ERROR: Address form was left blank"
                        messages.add_message(request, 40, msg)
                        p (msg)
                    if regformform_person[0].cleaned_data == {}:
                        msg="ERROR: Camper #1 form was left blank"
                        messages.add_message(request, 40, msg)
                        p (msg)
                    for m in regformform_person.errors:
                        p ("m",m)
                        messages.error(request, m)

                    
                    #reload the form and give the user a chance to fix whatever before anything is saved
                    #hopefully the messages are useful.
                    p("re-rendering the regform to correct for errors")
                    return render(request,'membership/registration_form.html',{ 
                        'membership_valid_from':membership_valid_from,
                        'membership_valid_to':membership_valid_to,
                        'registration_options':registration_options,
                        'registrationform': registrationform,
                        'registration': registration, ##used in template only
                        #'registrationoptions': registrationoptions,
                        #'rebates': rebates,
                        'regformform_person': regformform_person,
                        }) 

                p('DEBUG: Blank form check - PASS')


            ####BASE FORM SAVED HERE#####


            #All good!?  Save the registration now to obtain the PK
            #hopefully all the errors have been caught, otherwise there will be a lot of duplicates.
            newregistration=registrationform.save(commit=False)
            #p ("newregis",dir(registrationform))
            #p ("newregis2",(registrationform.has_changed()))
            if edit_view is True:
                registration_pk=registration_id

            #if there are no changes to the regform, this won't get triggered.
            for l in newregistration:
                    p ("Registration form saved",dir(l))
                    l.save()
                    registration_pk=l.pk

                    #this is messy - keyig the transaction id off date and PK is a good idea, but we have to save the form twice.  
                    #once to get the PK, and once to save the transaction_id.
                    l.transaction_id=str(now.year)+str(registration_pk)
                    l.save()


            registration=CampRegistration.objects.get(pk=registration_pk)
            #re-init the camper forms here otherwise the below fails because django thinks the base regform has not been saved yet
            regformform_person=PersonFormset(request.POST,instance=registration)

            #Could these checks possibly fail?  
            if regformform_person.is_valid() :
                saved=regformform_person.save(commit=False)
                for r in saved:
                        r.save()
                        p ("save adult form",r)
                messages.success(request, "Saved Successfully! Registration ID: "+str(registration_pk))

                #add the memnuid_id to the session so user can come back later
                session_registrations=[]
                if request.session.get('registration'):
                    session_registrations=request.session['registration']

                session_registrations.append(registration_pk)
                p("Form saved - registration_id", registration_pk, " setting session to",session_registrations)
                request.session['registration']=session_registrations
                save_success=True
            else:
                if not regformform_person.is_valid():
                    p ("regformform_person not valid", (regformform_person.errors))
                    for m in regformform_person.errors:
                        messages.error(request, m)
                    i=0
                p("regform adult or child not valid - second pass")

        else:
            if not registrationform.is_valid():
                p ("registration not valid", (registrationform.errors))
                for m in registrationform.errors:
                    messages.error(request, m)
                i=0
                for r in registrationform:
                        p (r.changed_data)
                        for c in r.changed_data:
                            p ("DEBUG: [%s] BASE form field %s went from \"%s\" to \"%s\"" % (str(registration.pk),c,r[c].initial, r[c].data))
                        i=i+1
            if not regformform_person.is_valid():
                p ("regformform_person not valid", (regformform_person.errors))

membership/templates/membership/breadcrumbs.html
    <div class="my_breadcrumb d-print-none">
          <ul class="breadcrumb">
          <li class="breadcrumb-item"><a href="https://tifd.org/texas-camp/">Texas Camp</a></li>
	  {% if registration.id %}
		<li class="breadcrumb-item"><a href="{% url 'camp:create'%}{{registration.id}}">My Registration</a></li>
          	<li class="breadcrumb-item"><a href="{% url 'camp:confirm' registration.id%}">Confirm</a></li>
          {% endif %}
  	{% if registration.agreecheckbox %}
          	<li class="breadcrumb-item"><a href="{% url 'camp:final' registration.id %}">Final Payment</a></li>
          {% endif %}
	{% if not registration.id %}
          <li class="breadcrumb-item"><a href="{% url 'camp:create'%}">New Registration</a></li>
          {% endif %}

        </ul>
   </div>

                {% if 'camp:final' in request.resolver_match.view_name %}
		{% endif %}

membership/templates/membership/crispy_header.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<style>

.requiredField { font-weight:bold; text-decoration: underline;}
.asteriskField { color: red; display:none;}

</style>
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

membership/templates/membership/debug.html
	{% extends 'membership/reports_header.html' %}
{% block content %}

<div class="row">

<!--
<div class="col s12">
<h3> Year: {{ thisyear }}</h3>
</div>
-->

{{form}}
<form action="" method=POST>

	{% csrf_token %}
	    {{ formset.management_form }}

<button type="submit" class="btn btn-primary">Sign in</button>
<input type="submit" value="Submit">
<h1>formset:</h1>{{formset}}<h1> /formset:</h1>

</form>

{% endblock %}

membership/templates/membership/detail.html
<h1>{{ membershipmemunit.mailingname }}</h1>

<table>
{% for name, value in membershipmemunit.get_fields %}
  {% if value %}
  <tr><td>{{ name }} <td> {{ value }}
  {% endif %}
{% endfor %}

membership/templates/membership/help.html
{% include "camp/header.html" %}
<div class="container ">

	<!--
<ul class="list-group">
	<button type="button" class="list-group-item list-group-item-action active">Texas Camp  {% now "Y" %} Registration Help</button>
	<li class="list-group-item">A <b>Part-time</b> registration means after lunch on Friday through close of Camp.</li>
	<li class="list-group-item"><b>Non-dancer</b> means any camper with physical challenges which prevent dancing, or a camper's family member who does not participate in Camp activities (classes, etc). Rate is not available to part-timie campers, scholarship recipients, or anyone receiving a staff discount.</li>
	<li class="list-group-item">Full scholarship recipients are required to pay the $15 annual TIFD membership fee</li>
	<li class="list-group-item">For camp details see the the <a href="https://tifd.org/texas-camp/">Texas Camp page on tifd.org</a></li>
	<li class="list-group-item">To apply for a scholarship please see our <a href="https://tifd.org/texas-camp/registration/">Registration Information Page</a> for details.</li>
	<li class="list-group-item">If you need further assitance or have other questions, feel free to contact us at payments [at] tifd.org</li>
	-->

</div>

membership/templates/membership/membershipcamper_form.html
testform.html

membership/templates/membership/navbar-backup.html
        <nav id="sidebar">

            <div class="col-sm-0 p-2 m-0">
                  <div class="card" style="width: 18rem;">
                  <div class="card-header">
                          Admin functions
                  </div>
                  <ul class="list-group list-group-flush">
			  <li class="list-group-item"><a href="{% url "membership:registrar" %}?year={{thisyear}}">Manage {{thisyear}} camp registrations</a><br>
			  <li class="list-group-item"><a href="{% url "membership:reports_by_slug" "camproster" %}?year={{thisyear}}">List of campers for {{thisyear}}</a><br>
				  <li class="list-group-item"><a href="{% url "membership:editcampers" %}">Edit a camp registration</a></li>
					  <li class="list-group-item"><a href="{% url "membership:payments" %}">Manage Payments</a></li>
                          <li class="list-group-item"><a href="/admin/membership/membershipmemunitproxy/add/">Add TIFD members</a></li>
				  <li class="list-group-item"><a href="{% url "membership:memunit_add" %}">Add camper - NEW MEMBER</a></li>
                          <li class="list-group-item"><a href="/membership/">List of TIFD members in current standing</a></li>
                          <li class="list-group-item"><a href="/newcampers">Add camper - EXISTING MEMBER</a></li>
                  </ul>
                  </div>

            </div>

            <div class="col-sm-0 p-2 m-0">
                  <div class="card" style="width: 18rem;">
                  <div class="card-header">
                          Reports for {{thisyear}}
                  </div>
                  <ul class="list-group list-group-flush">
                  {% for r in reports %}
                  <li class="list-group-item"><a href="{% url 'membership:reports_home' %}/{{r.slug}}{% if request.GET.year %}?year={{request.GET.year}}{%endif%}">{{r.title}}</a><br><small>{{r.description}}</small></li>
                   {% endfor %}
                  </ul>
                </div>
            </div>
        </nav>

membership/templates/membership/navbar.html
        <nav id="sidebar">

            <div class="col-sm-0 p-2 m-0">
                  <div class="card" style="width: 18rem;">
                  <div class="card-header">
                          Admin functions
                  </div>
                  <ul class="list-group list-group-flush">
			  <li class="list-group-item"><a href="{% url "membership:registrar" %}?year={{thisyear}}">Manage {{thisyear}} camp registrations</a><br>
			  <li class="list-group-item"><a href="{% url "membership:reports_by_slug" "camproster" %}?year={{thisyear}}">List of campers for {{thisyear}}</a><br>
				  <li class="list-group-item"><a href="{% url "membership:editcampers" %}">Edit a camp registration</a></li>
					  <li class="list-group-item"><a href="{% url "membership:payments" %}">Manage Payments</a></li>
                          <li class="list-group-item"><a href="/admin/membership/membershipmemunitproxy/add/">Add TIFD members</a></li>
				  <li class="list-group-item"><a href="{% url "membership:memunit_add" %}">Add camper - NEW MEMBER</a></li>
                          <li class="list-group-item"><a href="/membership/">List of TIFD members in current standing</a></li>
                          <li class="list-group-item"><a href="/newcampers">Add camper - EXISTING MEMBER</a></li>
                  </ul>
                  </div>

            </div>

            <div class="col-sm-0 p-2 m-0">
                  <div class="card" style="width: 18rem;">
                  <div class="card-header">
                          Reports for {{thisyear}}
                  </div>
                  <ul class="list-group list-group-flush">
                  {% for r in reports %}
                  <li class="list-group-item"><a href="{% url 'membership:reports_home' %}/{{r.slug}}{% if request.GET.year %}?year={{request.GET.year}}{%endif%}">{{r.title}}</a><br><small>{{r.description}}</small></li>
                   {% endfor %}
                  </ul>
                </div>
            </div>
        </nav>

membership/templates/membership/question_detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

membership/templates/membership/registrar.html
{% extends 'membership/bootstrap_header.html' %}

{% block content %}

{% if not pdf_view %}

<div class="d-flex" id="wrapper">
   {% include "membership/navbar.html" %}
{% endif %}

<div class="container-fluid">
<div class="row">
<div class="col-sm-12">
        <div class="table-responsive">
		{% if request.GET.q %}
		<!-- FILTER applied: "{{request.GET.q}}" -->
	{% endif %}
		<small>Results: {{ campers_adult|length }}</small>

<table class="table table-hover table-responsive-md table-striped bordered tablesorter" id=reporttable>
        <thead>
		<th>
		<th>ID
		<th>Address
		<th>Adult Campers
		<th>Registration
		<th>note
		<th>Status
                </thead>
                <tbody>


{% for regid,campers in mycampers.items %}

<!-- Camper Modal popup  -->
<div class="modal fade" id="mymodal-{{regid}}" tabindex="-1" role="dialog" aria-labelledby="mymodalLabel-{{regid}}" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="mymodalLabel-{{regid}}">Modify registration #{{regid}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
	      <form method=POST action="{% url "membership:registrar_update" regid %}">
		      {% csrf_token %}
		      <div class="form-group">
			<label for="paymentinput">Record Payment</label>
			<input name=payment type="number" class="form-control" id="paymentinput" placeholder="$">
		      </div>
		        <div class="form-group">
			    <label for="status">Change Status</label>
			    <select class="form-control" id="status" name="status">
				    {% for option in registration_status_options %}
				    <option value="{{option.id}}">{{option.status}}</option>
				    {%endfor %}

			    </select>
			 </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
	      </form>
      </div>
    </div>
  </div>
</div>
	

		<tr>
			<td><button class="btn-sm btn-primary text-light" data-toggle="modal" data-target="#mymodal-{{regid}}">Manage</button></td>
			<td><a href="{% url "camp:create_edit" regid %}">{{regid}}</a></td>
			<td> 
				{{campers.0.registration.address1}}<br>
				{% if campers.0.registration.address2 %}
				{{campers.0.registration.address2}}<br>
				{%endif %}
				{{campers.0.registration.city}}
				{{campers.0.registration.state}}
				{{campers.0.registration.zip}}
				
		<td>
			{%for camper in campers %}
			<a nowrap href="/admin/camp/camper_adult/{{camper.id}}">{{camper.first_name}} {{camper.last_name}}</a><br>
			{% endfor %}
			<td>
			{%for camper in campers %}
			{{camper.registration_type.description}}<br>
			{% endfor %}
		<td> {{campers.0.registration.camper_note}}
			<td> {% if campers.0.registration.registration_status.id == 6 or campers.0.registration.registration_status.id == 5 %}
				<span class="bg-success text-light font-weight-bold p-2 m-2 rounded">{{campers.0.registration.registration_status}}</span>

				{%elif campers.0.registration.registration_status.id == 3 or campers.0.registration.registration_status.id == 4 %}
					<span class="bg-warning text-black font-weight-bold p-2 m-2 rounded">{{campers.0.registration.registration_status}}</span>
				{%elif campers.0.registration.registration_status.id == 7 %}
					<span class="bg-danger text-light font-weight-bold p-2 m-2 rounded">{{campers.0.registration.registration_status}}</span>
				{%else%}
				<span class="bg-secondary text-light font-weight-bold p-2 m-2 rounded"> {{campers.0.registration.registration_status}}</span>
				{%endif%}
{% endfor %}

	</tbody></table>
	</div>

	{% include "membership/tablesort.html" %}
{% endblock %}

membership/templates/membership/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

membership/templates/membership/searchcampers.html
{% extends 'membership/bootstrap_header.html' %}

{% block content %}

        {% if user.is_authenticated %}
                     You are logged in as {{user.username|title}}
		     <h3>Home Page</h3>

    {% include "membership/year_selector.html" %}

<div class="row">
    <div class="col-sm-3">
    <form method='GET'>
  <input type='text' name='q' value='{{ request.GET.q }}'>
  <input class="button" type='submit' value="Search">
</form>


</div>

{%endif%}
{% endblock %}