camp/urls.py
from django.conf import settings
from django.urls import path
from django.contrib import admin
from django.conf.urls import include

from . import views


if settings.DEBUG:
    import debug_toolbar

app_name='camp'
urlpatterns = [
    path('', views.create, name='create'),
    #camp registration
        #/new/
        #/new/confirm/
        #/new/edit/  <--- an alias to confirm
        #/new/save/
    path('create/', views.create, name='create'),
    path('create/<int:registration_id>', views.create, name='create_edit'),
    path('delete/camper/<int:registration_id>', views.deletecamper, name='deletecamper'),
    path('delete/registration/<int:registration_id>', views.delete_entire_registration, name='delete_entire_registration'),
    path('donaterebate/<int:registration_id>', views.donaterebate, name='donaterebate'),
    path('confirm/<int:registration_id>', views.confirm, name='confirm'),
    path('final/<int:registration_id>', views.final, name='final'),
    path('final/', views.final, name='final'),
    path('status/<int:registration_id>', views.status, name='status'),
    path('checkpayment/<int:registration_id>', views.checkpayment, name='check_payment'),
    path('paypalpayment/<int:registration_id>', views.paypalpayment, name='paypal_payment'),
    path('paypalreturn/<int:registration_id>', views.paypalreturn, name='paypal_return'),
    path('test/500', views.my500, name='test_500'),
    path('help/', views.help, name='help'),
    path('check_membership/', views.check_membership, name='check_membership'),
    path('help/<slug>', views.help, name='help_slug'),
    path("view", views.homepage, name="homepage"),
    path("test", views.test, name="test"),
    path("test/", views.test, name="test"),
]

registrar/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import include

from . import views

admin.site.site_header = 'Database Admin Panel'
admin.site.site_title = 'Database Admin Panel'


app_name='registrar'
urlpatterns = [
    path("", views.homepage, name="homepage"),
    path('reports', views.reports_home, name='reports_home'),
    path('docs', views.docs, name='docs'),
    path('payments', views.payments, name='payments'),
    path('payments/add', views.payments_add, name='payments_add'),
    path('payments/report', views.payments_report, name='payments_report'),
    path('payment/view/<int:payment_id>', views.payment_view, name='payment_view'),
    path('payment/ipn_view/<int:ipn_id>', views.ipn_view, name='ipn_view'),
    path('payments/delete/', views.payments_delete, name='payments_delete'),
    path('payments/delete/<int:payment_id>', views.payments_delete, name='payments_delete'),
    path('payments/edit/<int:payment_id>', views.payments_add, name='payments_add_edit'),
    path('payments/quick/<int:registration_id>', views.payments_quick, name='payments_quick'),
    path('registrar', views.registrar, name='registrar'),
    path('campconstants', views.campconstants, name='campconstants'),
    path('membership_report', views.membership_report, name='membership_report'),
    path('membership_report/<slug>', views.membership_report, name='membership_report'),
    path('registrar/update/<int:registration_id>', views.registrar_update, name='registrar_update'),
    path('adjustment/add', views.adjustment_add, name='adjustment_add'),
    path('approve/<int:registration_id>', views.approve, name='approve'),
    path('refund_report/', views.refund_report, name='refund_report'),
    path('refund/<int:registration_id>', views.refund, name='refund'),
    path('reports/<report_by_slug>', views.report_by_slug, name='reports_by_slug'),
    path('deposit', views.deposit, name='deposit'),
    path('donationletter/<int:registration_id>', views.donationletter_endpoint, name='donationletter'),
    path('view/<int:registration_id>', views.view, name='view'),
    path('renew', views.view, name='renew'),

]

tifddb/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

handler500 = 'camp.views.my500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include('camp.urls')),
    path('registrar/', include('registrar.urls')),
    path('membership/', include('membership.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('nested_admin/', include('nested_admin.urls')),
    re_path(r'^paypal_notify/', include('paypal.standard.ipn.urls')),


]

registrar/models.py
from django.db import models
from django.forms import ModelForm
from camp.models import *
from camp.custom.mylogger import p

registrar/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, reverse, redirect
from django.template import loader
from django.http import Http404, HttpResponseRedirect
from django.contrib import messages
from django.template.loader import render_to_string
from django.db.models import Q, Count
from django.forms import modelformset_factory, Textarea, TextInput, DateInput
from django.forms import inlineformset_factory
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.template.loader import get_template
from django.contrib.auth.decorators import user_passes_test

from camp.models import *
from camp.custom.mylogger import p
from camp.custom.tday import tday
try:
    from camp.constants import dvd_price_decimal,membership_price_decimal,linens_price_decimal
    from camp.views import get_discount,  emailconfirmation, generate_email_html, get_membership_info, generate_cart_from_registration, get_active_housing_options,get_active_registration_options
except: pass

from paypal.standard.ipn.models import PayPalIPN

from .forms import *
from .models import *

from decimal import Decimal
from io import BytesIO
from xhtml2pdf import pisa

import re
import csv
import datetime

now = datetime.datetime.now()
years = list(reversed(range(2004, datetime.datetime.now().year+2)))
        #range() does not include the final number in the range)

def get_thisyear(request):
    now = datetime.datetime.now()
    if request.GET.get('year'):
        thisyear=int(request.GET.get('year'))
    elif request.session.get('year'):
        thisyear=request.session.get('year')
        p("thisyear: session found")
    else:
        thisyear=datetime.datetime.now().year
        p("thisyear: no session found")

    p("thisyear:",thisyear)
    request.session['year']=thisyear

    #thisyear should be returned as a string since that's what the HTTP reuqest object returns
    return int(thisyear)

def registrar_check(user):
        return user.groups.filter(name__in=['registrar',])
def readonly_check(user):
        return user.groups.filter(name__in=['registrar','readonly'])

def render_to_pdf(template_src, request, context_dict={},pdf_only=False):
    template = get_template(template_src)
    context_dict['pdf_view']=True
    html  = template.render(context_dict,request)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), result)
    if pdf_only:
        return result.getvalue()
    else:
        if not pdf.err:
            return HttpResponse(result.getvalue(), content_type='application/pdf')
        return None


@login_required
@user_passes_test(registrar_check)
def docs(request):
    thisyear=get_thisyear(request)
    registration_status_options=CampRegistrationStatus.objects.all()
    return render(request, 'registrar/docs.html', {
        'years':years,
        'thisyear':thisyear,
        'registration_status_options':registration_status_options,
        "reports": MembershipReport.objects.all,
        })

@login_required
@user_passes_test(readonly_check)
def homepage(request):
    thisyear=get_thisyear(request)
    p("homepage thisyear",thisyear)

    registration_status_options=CampRegistrationStatus.objects.all()
    payments_waiting_for_deposit=MembershipPayments.objects.filter(waiting_for_deposit__exact=1).filter(date_recd__year=thisyear).select_related('registration').select_related('membership_person')

    c=CampCamper.objects.filter(registration__year=thisyear).order_by('-pk').select_related('registration_type').select_related('registration'). \
            select_related('registration__registration_status'). \
            order_by('registration'). \
            exclude(registration__email_confirmation_sent=1)

    unconfirmed_campers,registration_stats=generate_mycampers_dict(c)

    c=CampCamper.objects.filter(registration__year=thisyear).order_by('-pk').select_related('registration_type').select_related('registration').select_related('registration__registration_status').order_by('registration')
    all_campers,registration_stats=generate_mycampers_dict(c)

#MariaDB [tifddb1]> select * from camp_registration_status;
#+----+----------------------------+-----------------------------------------------------------------------------------------+---------------+
#| id | status                     | description                                                                             | display_order |
#+----+----------------------------+-----------------------------------------------------------------------------------------+---------------+
#|  1 | Incomplete                 | User has saved the first page, not the second (no agree checkbox)                       |            10 |
#|  2 | NotPaid                    | User has saved the 2nd page (confirmed alcohol policy), not selected a payment type yet |            20 |
#|  3 | Waiting for PayPal payment | User pushed the PayPal button and we have not yet confirmed their paypal payment        |            30 |
#|  4 | Waiting for check payment  | User pressed the check payment button and we have not yet approved their payment        |            40 |
#|  5 | Registrar Approved         | Registrar confirmed payment                                                             |           100 |
#|  6 | Paypal IPN confirmed       | We received a successful IPN response from PayPal                                       |            60 |
#|  7 | Paypal IPN error           | Error code when something went wrong with paypal IPN (set in camp/signals.py)           |          NULL |
#|  8 | PAID via registrar         | Registrar has processed payment and the registration is paid in full                    |            50 |
#|  9 | Imported from old DB       |                                                                                         |          NULL |
#+----+----------------------------+-----------------------------------------------------------------------------------------+---------------+

    return render(request, 'registrar/index.html', {
        'payments_waiting_for_deposit':payments_waiting_for_deposit,
        'years':years,
        'return':"home",
        'PAYMENT_TYPES':PAYMENT_TYPES,
        'registration_status_options':registration_status_options,
        'thisyear':thisyear,
        'unconfirmed_campers':unconfirmed_campers,
        'all_campers':unconfirmed_campers,
        'registration_stats':registration_stats,
        "reports": MembershipReport.objects.all,
        })

@user_passes_test(readonly_check)
@login_required
def reports_home(request):
    return render(request=request,
              template_name='registrar/reports_home.html',
              context={
                  "report": MembershipReport.objects.all,
              })

@user_passes_test(readonly_check)
@login_required
def refund_report(request):
    ##this is no longer used
    thisyear=get_thisyear(request)
    payments=MembershipPayments.objects.filter(created_at__year=thisyear).filter(registration__registration_status_id__in=REGISTRATION_PAID_STATUS).filter(registration__registration_source=0).filter(registration__payment_type="paypal").filter(registration__id__gt=10664)

    total_gross=0
    for pp in payments:
        total_gross+=pp.gross_amt

    return render(request=request,
              template_name='registrar/reports_refund_covid.html',
              context={
                  "payments":payments,
                  "thisyear":thisyear,
                  "total_gross":total_gross,
                  "reports": MembershipReport.objects.all,
              })

@user_passes_test(readonly_check)
@login_required
def report_by_slug_render(request, report_by_slug,fields,result_dict,thisyear,page_title='',template='registrar/reports_generic.html',hidden_fields=('registration',), extra={}):

        thisyear=get_thisyear(request)
        headers=[]
        searchfields=[]
        result_list=[]
        filename="report.csv"

        slugs = [c.slug for c in MembershipReport.objects.all()]
        if report_by_slug in slugs:
            matching_report = MembershipReport.objects.get(slug=report_by_slug)
            page_title=matching_report.title
            filename=str(matching_report.title)+".csv"

        #it would be better to pull this out of models.verbose_name but I could not figure out a clean way to do it.
        for f in fields:
            if next(iter(f)) not in hidden_fields:
                  headers+=f.values()
                  searchfields+=f

        for x in result_dict:
            if x not in hidden_fields:

        ###CAREFUL WITH DEBUG PRINT STATEMENTS IN HERE
        # it will fail with a log message similar to:  'ascii' codec can't encode character '\xa9' in position 175: ordinal not in range(128)
                result_list+=x.values(),

        context={
                    "result_list": result_list, 
                    "result_dict": result_dict,
                    'headers':headers,
                    'years':years,
                    'thisyear':thisyear,
                    'hidden_fields':hidden_fields,
                    "page_title": page_title,
                    "extra": extra,
                    "reports": MembershipReport.objects.all(),
                    }
                
        if request.GET.get('csv'):
            #filename="camp_roster.csv"
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="'+filename+'"'
            writer = csv.writer(response)

            headers_without_hidden_fields=[]
            for f in fields:
                headers_without_hidden_fields+=f.values()

            writer.writerow(headers_without_hidden_fields)


            for r in result_list:
                writer.writerow(r)
            return response

        if request.GET.get('pdf'):

registrar/templates/registrar/camperlist.html
{% for instance in field_names %}
    {% for field, value in instance.fields.items %}
    {{ field }}: {{ value }}<br>
    {% endfor %}
{% endfor %}

registrar/templates/registrar/deposit.html
{% extends 'registrar/bootstrap_header.html' %}

{% block content %}

{% if not pdf_view %}

<div class="d-flex" id="wrapper">
{% endif %}

{% if pdf_view %}
        <!-- STYLE FOR THE PDF VIEW ONLY -->
        <style>
        th, td {
          border-bottom: 1px solid #ddd;
        padding: 5px;
        }
        a {
          color: black;
          text-decoration:none;
        }
        .email { display:noe;}
        </style>

{% endif %}
<div class="container">
<div class="row">
	<div class="col-sm-2">
		Deposit date
	</div>
	<div class="col-sm-2">
	<form method=POST action="{% url "registrar:deposit" %}">
		<input id=deposit_date type=date name=deposit_date value="{% now "Y-m-d" %}" class="form-control">
	</div>
	<div class="col">
	<a href="{% url "registrar:payments" %}"><button type=submit class="btn btn-primary" value=Return>Save</button></a>
	</div>
<div class="col-sm-12">

	{% csrf_token %}


<table class="table table-hover table-responsive-md table-striped bordered tablesorter" id=reporttable>
        <thead><tr>
			<th>ID
			<th>Registration
			<th>Date Recv
			<th>Who has
			<th>Type
			<th>Waiting for deposit
			<th>Notes
			<th>Total

               </tr>
	</thead>
        <tbody>



{% for payment in payments %}
<input type=hidden name=payments id=payments value="{{payment.id}}">

<tr>
	<td><a href="{% url "registrar:payments_add_edit" payment.id %}?return=payments">{{payment.id}}</a></td>
	<td>
		{%if payment.registration %}{{payment.registration|default_if_none:""}}
		{%elif payment.membership_person %}{{payment.membership_person}}
		{%else%}No person / No Registration
		{%endif%}
	</td>
	<td>{{payment.date_recd|date:"SHORT_DATE_FORMAT"}}</td>
	<td>{{payment.who_has_possession}}</td>

	{%comment%}
	see also: camp/templates/camp/shopping_cart_table.html
	{%endcomment%}
	<td>
		{% if payment.paypal_fee > 0 %}
			PayPal
		{%elif payment.check_num %}
		Check #{{payment.check_num}}
		{%elif payment.cash %}
			Cash
		{%endif%}

	</td>

	<td>{% if payment.waiting_for_deposit %}Yes
		{% else %}No
		{%endif%}
	</td>
	<td class="small">{{payment.notes|default_if_none:""}}</td>
	<td>{{payment.gross_amt}}</td>
</tr>
{% endfor %}

	</tbody></table>
	</div>
	<input type="hidden" name=save value=save>
	{% csrf_token %}
	<a href="{% url "registrar:payments" %}"><button type=submit class="btn btn-primary" value=Return>Save</button></a>
</form>

{% endblock %}

</div></div>

registrar/templates/registrar/manage_articles.html
<form method="post">
    {{ formset.management_form }}
    <table>
        {% for form in formset %}
        {{ form }}
        {% endfor %}
    </table>
</form>

registrar/templates/registrar/payment_view.html
        <div class="container bg-white border border-secondary">
                <div class=row>
                   <div class="col text-dark">
			   {% for key, val in payment.items %}
			   {{key}},{{val}}<br>
			   {%endfor%}
                </div>


        </div>


        </body>

registrar/templates/registrar/payments.html
{% extends 'registrar/bootstrap_header.html' %}

{% block content %}

{% if not pdf_view %}

<div class="d-flex" id="wrapper">
{% endif %}

{% if pdf_view %}
        <!-- STYLE FOR THE PDF VIEW ONLY -->
        <style>
        th, td {
          border-bottom: 1px solid #ddd;
        padding: 5px;
        }
        a {
          color: black;
          text-decoration:none;
        }
        .email { display:noe;}
        </style>

{% endif %}
<div class="container">
<div class="row">
<div class="col-sm-12">
	<form method=POST action="{% url "registrar:deposit" %}">

		{% if request.GET.q %}
		<!-- FILTER applied: "{{request.GET.q}}" -->
	{% endif %}
		<small>Results: {{ payments|length }}</small>

		<a class=d-none href="{% url 'registrar:payments_add'%}?return=payments">Add new payment</a>

	{% csrf_token %}
	<div class="row">
		<div class="col-9 m-2">
			Showing all payments for {{thisyear}}.  Click the checkbox next to a payment to add to a deposit slip.
		</div>
		<div class="col ">
		<button type=submit class=" float-right btn btn-primary" value=Save>Deposit</button>
		</div>
	</div>

        <div class="table-responsive">


<table class="table table-hover table-responsive-md table-striped bordered tablesorter" id=reporttable>
        <thead><tr>
			<th class="sorter-false"><input type="checkbox" id="checkAll" name="payments-th" value="">
			<th>ID
			<th>Registration
			<th>Date Recv
			<th>Who has
			<th>Type
			<th>Waiting for deposit
			<th>Notes
			<th>Total
			<th class="sorter-false">

               </tr>
	</thead>
        <tbody>



{% for payment in payments %}
<tr>
	<td>{% if payment.waiting_for_deposit %}
		<input type="checkbox" id="payments" name="payments" value="{{payment.id}}">
		{%endif%}
	</td>
	<td><a href="{% url "registrar:payments_add_edit" payment.id %}?return=payments">{{payment.id}}</a></td>
	<td>
		{%if payment.registration and payment.registration_id != 1%}{{payment.registration|default_if_none:""}}
		{%elif payment.membership_person %}{{payment.membership_person}}
		{%elif payment.pp_ipn_name %}{{payment.pp_ipn_name}}<br>{{payment.pp_ipn_email}}
		{%else%}No person / No Registration
		{%endif%}
	</td>
	<td>{{payment.date_recd|date:"SHORT_DATE_FORMAT"}}</td>
	<td>{{payment.who_has_possession}}</td>

	{%comment%}
	see also: camp/templates/camp/shopping_cart_table.html
	{%endcomment%}
	<td>
		{% if payment.paypal_fee > 0 %}
			PayPal
		{%elif payment.check_num %}
		Check #{{payment.check_num}}
		{%elif payment.cash %}
			Cash
		{%endif%}

	</td>

	<td>{% if payment.waiting_for_deposit %}Yes
		{% else %}No
		{%endif%}
	</td>
	<td class="small">{{payment.notes|default_if_none:""}}</td>
	<td>{{payment.gross_amt}}</td>
		<div id="payment_delete">
	<td>
		<a id="ayment_delete" href="{% url "registrar:payments_delete" payment.pk%}?return_to=payments" title="Delete Payment" onclick="return confirm('Are you sure you want to delete this payment')"><p class="h3">&times;</p></a></td>
		</div>
</tr>


{% endfor %}

		</tbody></table>
	</div>
	</form>

	{% include "registrar/tablesort.html" %}

<script>
	$(document).ready(function() {
	    $("#checkAll").click(function() {
        	var checkBoxes = $("input[name=payments");
        	checkBoxes.prop("checked", !checkBoxes.prop("checked"));
    });
});


</script>
{% endblock %}

</div></div>

registrar/templates/registrar/registrar.html
{% extends 'registrar/bootstrap_header.html' %}




{% block content %}
<!--
<link rel="stylesheet" href="/static/jquery-ui-1.12.1.custom/jquery-ui.min.css" type="text/css" />
<script src="/static/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
-->

<link rel="stylesheet" href="/static/jquery.qtip.css" type="text/css" />
<script src="/static/jquery.qtip.min.js"></script>

<style>
.qtip { 
	max-width: none !important; 
	font-size: 18px !important;
}

</style>

{% load mathfilters %}
{% if not pdf_view %}

<div class="d-flex" id="wrapper">
{% endif %}

<div class="container-fluid">
<div class="row">
<div class="col-sm-12">
	<div class="row">
		<div class="small col">
				Total campers (paid and unpaid): {{ number_of_campers }}
				Total owed: {{registration_header_info.total_owed}}
				Total revcd: {{registration_header_info.total_gross}}
				Total PayPal fees: {{registration_header_info.total_pp_fees}}
				Outstanding: {{registration_header_info.outstanding}}
		</div>
	</div>
	<div class="row">
		<div class="col">
			<form method=GET>
				Filters -  
				Email sent: <input type=checkbox name=email_sent {% if email_sent %}checked{%endif%}> 
				Paid: <input type=checkbox name=paid {% if paid %}checked{%endif%}>
				Camp only: <input type=checkbox name=camponly {% if camponly %}checked{%endif%}>
				Membership only: <input type=checkbox name=memonly {% if memonly %}checked{%endif%}>
			        <button type="submit" class="btn-primary btn-sm">Apply</button>

			</form>
		</div>
	</div>
	<div class="table-responsive" id="maintable">

<table class="table table-hover table-responsive-md table-condensed tablesorter" id=reporttable>
        <thead>
		<th>
		<th>Campers
		<th>Date Recd 
		<th>Note&nbsp;from&nbsp;camper
		<th>Cart&nbsp;total
		<th>Payments
		<th>Owed
		<th>Payment Status
		<th>Registration Status
                </thead>
                <tbody>

{% for regid,campers in mycampers.items %}

	<tr >
		<td>
			{% include "registrar/camper_actions.html" %}
			</td>


					<td nowrap >
						{% include "registrar/camper_names.html" %}
	<script>

		$('.viewpop{{forloop.counter0}}').qtip({
				content: {
				text: 'Loading...', // The text to use whilst the AJAX request is loading
				ajax: {
					url: '{% url "registrar:view" regid %}', // URL to the local file
					type: 'GET', // POST or GET
					data: {}, // Data to pass along with your request
					success: function(data, status) {
						// Process the data
						// Set the content manually (required!)
						this.set('content.text', data);
					}
				}
			},
				style: {
       				classes: 'qtip-dark',
				width: 900, // Overrides width set by CSS (but no max-width!)
				height: 500 // Overrides height set by CSS (but no max-height!)
			},
			     	show: { delay: 0, solo: true},
     				hide: { fixed: true, delay: 200 },
			    position: { 
				        my : 'left top',
    					at : 'right top',
				    	adjust : {
				       	screen : true
	    				}
			    }


	});
	</script>

		<td nowrap> 
			{% if campers.0.registration.postmark %}
			{{campers.0.registration.postmark|date:'Y-m-d'}}
			{%else%}
			{{campers.0.registration.created_at|date:'Y-m-d'}}
			{%endif%}

		</td>
		<td>{{campers.0.registration.camper_note|default_if_none:""}}
		<td>{{campers.0.registration.cart_total}}</td>
			<td>	 
				<table class="table-nested">
			      {% for p in campers.0.mypayments %}
			      <tr class="{% cycle 'bg-none' 'bg-none'%}"><td colspan=2><a href="{% url "registrar:payments_add_edit" p.id %}?return=registrar">{{p.gross_amt}}</a><td>
					{% if p.notes %}
					<td><i>"{{p.notes}}"</i></td>
					{%endif%}
	</tr>
			      {% endfor %}
				</table>
				<td>
					{{ campers.0.registration.cart_total|sub:campers.0.mypayments_total }}
				</td>
			      <td>

				    	{% if campers.0.registration.cart_total == campers.0.mypayments_total %}
					<span class="bg-success text-light font-weight-bold p-2 m-2 rounded text-nowrap">
						PAID IN FULL
					</span>
					{% elif campers.0.registration.cart_total < campers.0.mypayments_total %}
					<span class="bg-warning text-dark font-weight-bold p-2 m-2 rounded text-nowrap">
						OVERPAID
					</span>
					{%else %}
					<span class="bg-primary text-light font-weight-bold p-2 m-2 rounded text-nowrap">NOT PAID</span>

					{%endif%}

			<td nowrap> 
				{% include "registrar/registration_status.html" %}
			</td>


							
			</td>
{% endfor %}

	</tbody></table>
	</div>

	<script>
	function deposit_today() {
        var now = new Date();
        var day = ("0" + now.getDate()).slice(-2);
        var month = ("0" + (now.getMonth() + 1)).slice(-2);
        var today = now.getFullYear()+"-"+(month)+"-"+(day) ;
        $('#id_date_recd').val(today);
    //$("#id_depositdate").datepicker("setDate", new Date());
}
	</script>

	<script>
	$( document ).click(function() {
   		$('.ui-tooltip').remove();
	});

	</script>


	{% include "registrar/tablesort.html" %}
{% endblock %}

registrar/templates/registrar/reports_refund_covid.html
{% extends 'registrar/bootstrap_header.html' %}

{% block content %}


{% if pdf_view %}
        <!-- STYLE FOR THE PDF VIEW ONLY -->
        <style>
        th, td {
        border-bottom: 1px solid #ddd;
        padding-top: 3px;
	font-size:12px;
        }
        a {
          color: black;
          text-decoration:none;
        }
        .email { display:noe;}
        </style>

{% endif %}
<div class="container-fluid">
<div class="row">
<div class="col-sm-12">
        <div class="table-responsive">
		{% if request.GET.q %}
		<!-- FILTER applied: "{{request.GET.q}}" -->
	{% endif %}
	{% if not pdf_view %}
		Results: {{ payments|length }}
		Gross total: {{ total_gross }}
          <a href="?pdf=1&year={{thisyear}}&q={{ request.GET.q }}"><button class="btn btn-success my-sm-0" type="submit">PDF</button></a> 
          <a href="?csv=1&year={{thisyear}}&q={{ request.GET.q }}"><button class="btn btn-success my-sm-0" type="submit">CSV</button></a>
	  {% endif %}

{% if request.GET.q and pdf_view %}
<p class="h3 bg-warning">Filter applied: "{{ request.GET.q }}"</p>
{%endif%}

<table class="table table-hover table-responsive-md table-striped bordered tablesorter" id=reporttable>
        <thead><tr>
				<th align= "left">Registration</th>
				<th align= "left">PP IPN</th>
				<th align= "left">pmt.Gross</th>
				<th align= "left">pmt.mem</th>
				<th align= "left">pmt.PPfee</th>
				<th align= "left">pmt.refund</th>
				<th align= "left">cart_total</th>
                </tr></thead>
                <tbody>

{% for result in payments %}

<tr>
	<td nowrap>
		<a href="{% url "registrar:payments_add_edit" result.pk%}">{{result.registration}}</a>
	</td>
	<td nowrap>
		&nbsp;[<a href="https://www.paypal.com/activity/payment/{{result.pp_ipn_txn_id}}">{{result.pp_ipn_txn_id}}</a>]
	</td>

	<td nowrap>{{result.gross_amt}} </td>
	<td nowrap>{{result.membership_fee}} </td>
	<td nowrap>{{result.paypal_fee}} </td>
	<td nowrap>{{result.refund_amt}} </td>
	<td nowrap>{{result.registration.cart_total}} </td>
</tr>
{% endfor %}

		</tbody></table>
	</div>

	{% include "registrar/tablesort.html" %}
{% endblock %}


</div></div>

registrar/templates/registrar/spew.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8" />

<body>

{%for element in listDict%}
    {{ element.product }} - {{ element.price }}
{% endfor %}