camp/urls.py
from django.conf import settings
from django.urls import path
from django.contrib import admin
from django.conf.urls import include

from . import views


if settings.DEBUG:
    import debug_toolbar

app_name='camp'
urlpatterns = [
    path('', views.create, name='create'),
    #camp registration
        #/new/
        #/new/confirm/
        #/new/edit/  <--- an alias to confirm
        #/new/save/
    path('create/', views.create, name='create'),
    path('create/<int:registration_id>', views.create, name='create_edit'),
    path('delete/camper/<int:registration_id>', views.deletecamper, name='deletecamper'),
    path('delete/registration/<int:registration_id>', views.delete_entire_registration, name='delete_entire_registration'),
    path('donaterebate/<int:registration_id>', views.donaterebate, name='donaterebate'),
    path('confirm/<int:registration_id>', views.confirm, name='confirm'),
    path('final/<int:registration_id>', views.final, name='final'),
    path('final/', views.final, name='final'),
    path('status/<int:registration_id>', views.status, name='status'),
    path('checkpayment/<int:registration_id>', views.checkpayment, name='check_payment'),
    path('paypalpayment/<int:registration_id>', views.paypalpayment, name='paypal_payment'),
    path('paypalreturn/<int:registration_id>', views.paypalreturn, name='paypal_return'),
    path('test/500', views.my500, name='test_500'),
    path('help/', views.help, name='help'),
    path('check_membership/', views.check_membership, name='check_membership'),
    path('help/<slug>', views.help, name='help_slug'),
    path("view", views.homepage, name="homepage"),
    path("test", views.test, name="test"),
    path("test/", views.test, name="test"),
]

membership/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import include

from . import views

admin.site.site_header = 'Database Admin Panel'
admin.site.site_title = 'Database Admin Panel'

app_name='membership'

urlpatterns = [
    path("", views.create, name="create"),
    path('<int:registration_id>', views.create, name='create_edit'),
    path('help/', views.help, name='help'),
    path("create/", views.create, name="create"),
    path('create/<int:registration_id>', views.create, name='create_edit')
]

tifddb/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

handler500 = 'camp.views.my500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include('camp.urls')),
    path('registrar/', include('registrar.urls')),
    path('membership/', include('membership.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('nested_admin/', include('nested_admin.urls')),
    re_path(r'^paypal_notify/', include('paypal.standard.ipn.urls')),


]

camp/views.py
from django.http import HttpResponse, HttpResponseServerError, Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, reverse, redirect
from django.template import loader
from django.contrib import messages
from django.forms import modelformset_factory, Textarea, TextInput, DateInput, ValidationError, BooleanField
from django.forms import inlineformset_factory
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMultiAlternatives,EmailMessage
from django.core import mail
from django.template.loader import render_to_string
from django.conf import settings
from django.template import Context, Template

from paypal.standard.forms import PayPalPaymentsForm

from .forms import *
from .models import *

import random
import string
import re
import datetime
import html2text
import logging

from .custom.mylogger import p

try:
    from .constants import linen_price,linen_price_decimal,dvd_price,dvd_price_decimal,membership_price,membership_price_decimal,shipping_price,shipping_price_decimal
except: pass

def my500(request):
    t = loader.get_template('camp/500.html')
    response = HttpResponseServerError(t.render())
    response.status_code = 500
    return response

def randomString(stringLength=10):
    """Generate a random string of fixed length """
    letters = string.ascii_lowercase
    return ''.join(random.choice(letters) for i in range(stringLength))

def get_client_ip(request):
    ip=""
    try:
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
    except:
        pass
    return ip

def auth_check(request,registration_id):

        #return true if registration_id in the session, or if the user is in the "registrar" group
        try: request.session['registration']
        except KeyError: request.session['registration'] = []

        ip=get_client_ip(request)
        p(registration_id,"AUTH CHECK - registration_id:",registration_id, "session:",request.session['registration'], " path:", request.get_full_path(),"ip:",ip)
        session_registration=request.session['registration']

        if request.user.groups.filter(name__in=['registrar']).exists():
            p ('Registrar authenticated! registration_id',registration_id)
            return True
        elif request.user.groups.filter(name__in=['register_anytime']).exists():
            p ('Register anytime! registration_id',registration_id)
            return True
        elif registration_id in request.session['registration']:
            p ("Guest authenticated.",request.session['registration'])
            return True

        else: 
            p("auth failed. session:", request.session['registration'], " path:", request.get_full_path())
            return False

def get_list_of_registrations_from_session(request):

        try: request.session['registration']
        except KeyError: request.session['registration'] = []

        session_registration=request.session['registration']

        campers=CampCamper.objects.filter(registration__in=session_registration).order_by('-registration_id','pk')
        my_registration_dict={}
        for r in campers:
            if r.registration_id not in my_registration_dict.keys():
                my_registration_dict[r.registration_id]=[]
            my_registration_dict[r.registration_id].append(r)

        p("get list of registrations from session returned:",my_registration_dict)
        return my_registration_dict

def get_membership_info(first_name,last_name):
    modern_member=CampCamper.objects.filter(first_name__exact=first_name).filter(last_name__exact=last_name).exclude(membership_valid_to__exact=None).order_by("-membership_valid_to")[:1]
    legacy_member=MembershipPerson.objects.filter(first_name__exact=first_name).filter(last_name__exact=last_name).exclude(membership_valid_to__exact=None).order_by("-membership_valid_to")[:1]
    data={}

    if legacy_member:
        #if the legacy membership info is in the future
        #AND if it's farther ahead than the moderm record, spit it out
        #hopefully this is rare.
        #if (legacy_member[0].membership_valid_to > now.date()) and modern_member and legacy_member[0].membership_valid_to > modern_member[0].membership_valid_to:

        #if we have a legacy member and there is no modern member, return the legacy member
        #if we have both, only recturn legacy if membership_valid_to is greater than the modern member (should be rare)
        if not modern_member: p("no modern record found for", first_name, last_name)
        if modern_member and legacy_member[0].membership_valid_to > modern_member[0].membership_valid_to:
            p("older legacy record found for", first_name, last_name, "modern_valid", modern_member[0].membership_valid_to, "legacy valid", legacy_member[0].membership_valid_to)

        if (not modern_member) or (modern_member and legacy_member[0].membership_valid_to > modern_member[0].membership_valid_to):
            data['first_name']=legacy_member[0].first_name
            data['last_name']=legacy_member[0].last_name
            data['membership_valid_to']=legacy_member[0].membership_valid_to
            data['registration_source']=legacy_member[0].membership_type.membertype
            p("found legacy membership",legacy_member[0],legacy_member[0].id,legacy_member[0].registration_id,legacy_member[0].registration)
            return data,legacy_member

    if modern_member:
        data['first_name']=modern_member[0].first_name
        data['last_name']=modern_member[0].last_name
        data['membership_valid_to']=modern_member[0].membership_valid_to
        if modern_member[0].registration.registration_source==0:
            data['registration_source']="Texas Camp"
        else:
            data['registration_source']="Membership Renewal Form"

        p(f"found modern membership name:{modern_member[0]} id:{modern_member[0].id} regid:{modern_member[0].registration_id} reg:{modern_member[0].registration}")
        return data,modern_member

    else:
        p("get_membership_info returned nothing valid for",first_name,last_name)
        return data,modern_member
    return data,modern_member


def check_membership(request):

    if request.method == "POST":
        first_name=request.POST.get("first_name")
        last_name=request.POST.get("last_name")
        p("check membership query for",first_name,last_name)
        data,member=get_membership_info(first_name,last_name)
        if not data:
            data['failed_search']=True
            data['first_name']=first_name
            data['last_name']=last_name
            #messages.error(request, "Member not found!")

        return render(request,'camp/check_membership.html',{ 
            'data':data,
            })
    else:
        return render(request,'camp/check_membership.html',{ 
            }) 

def deletecamper(request,registration_id):
    if auth_check(request,registration_id) is not True: 
        return HttpResponse('<h1>Permission denied</h1>',status=403)

    camper_id=None
    if request.GET.get('delete_camper'):
        camper_id=int(request.GET.get('delete_camper'))
        mycamper=get_object_or_404(CampCamper,registration__exact=registration_id, pk=camper_id)
    if request.GET.get('delete_adult'):
        camper_id=int(request.GET.get('delete_adult'))
        mycamper=get_object_or_404(CampCamper,registration__exact=registration_id, pk=camper_id)
    if request.GET.get('delete_child'):
        camper_id=int(request.GET.get('delete_child'))
        mycamper=get_object_or_404(CampCamper,registration__exact=registration_id, pk=camper_id)
    registration_source=0

    if 'mycamper' in vars():
        registration_source=mycamper.registration.registration_source
        p("CAMPER DELETED:",camper_id,"reg source:",registration_source,mycamper.__dict__)
        mycamper.delete()
    else:
        p("CAMPER NOT FOUND! camper_id:",camper_id, " REG ID: ", registration_id)
    if registration_source==1:
        return HttpResponseRedirect(reverse('membership:create_edit',args=[registration_id]))
    else:
        return HttpResponseRedirect(reverse('camp:create_edit',args=[registration_id]))


def delete_entire_registration(request,registration_id):

    if auth_check(request,registration_id) is not True: 
        return HttpResponse('<h1>Permission denied</h1>',status=403)

    now = datetime.datetime.now()
    thisyear=request.GET.get('year') or str(now.year)

    myregistration=get_object_or_404(CampRegistration,pk=registration_id)
    mycampers=CampCamper.objects.filter(registration=registration_id)

    p("DELETE ENTIRE REGISTRATION CALLED for campers",mycampers," regid: ",registration_id)
    for c in mycampers:
        p("Deleted camper:",c.__dict__)
        try:
            c.delete()
        except:
            p("Camper delete dailed for ",c)

    p("Deleted registration:",myregistration.__dict__)
    myregistration.delete()

    return_url="%s?ts=%syear=%s" % (reverse('registrar:registrar'),now.microsecond,str(thisyear))
    return HttpResponseRedirect(return_url)


def donaterebate(request,registration_id):
    if auth_check(request,registration_id) is not True: 
        return HttpResponse('<h1>Permission denied</h1>',status=405)

    if request.method == "POST":

        registration=CampRegistration.objects.get(pk=registration_id)
        donationform = DonationForm(request.POST, instance=registration)
        rebateform = RebateForm(request.POST, instance=registration)
        campernotesform = CamperNotesForm(request.POST, instance=registration)
        safetypolicyform = SafetypolicyForm(request.POST, instance=registration)


        ##########################membership registration#######################
        if registration.registration_source==1: #0=camp, 1=membership

camp/templates/camp/breadcrumbs.html
{% if registration.registration_source == 1 %}
    <div class="my_breadcrumb d-print-none">
          <ul class="breadcrumb">
          <li class="breadcrumb-item"><a href="https://tifd.org/">TIFD</a></li>
	  {% if registration.id %}
		<li class="breadcrumb-item"><a href="{% url 'membership:create'%}{{registration.id}}">My Membership</a></li>
          	<li class="breadcrumb-item"><a href="{% url 'camp:confirm' registration.id%}">Confirm</a></li>
          {% endif %}
  	{% if registration.agreecheckbox %}
          	<li class="breadcrumb-item"><a href="{% url 'camp:final' registration.id %}">Final Payment</a></li>
          {% endif %}
	{% if not registration.id %}
          <li class="breadcrumb-item"><a href="{% url 'camp:create'%}">New Membership</a></li>
          {% endif %}

        </ul>
   </div>
  {% else %}
    <div class="my_breadcrumb d-print-none">
          <ul class="breadcrumb">
          <li class="breadcrumb-item"><a href="https://tifd.org/">TIFD</a></li>
	  {% if registration.id %}
		<li class="breadcrumb-item"><a href="{% url 'camp:create'%}{{registration.id}}">Camp Registration</a></li>
          	<li class="breadcrumb-item"><a href="{% url 'camp:confirm' registration.id%}">Confirm</a></li>
          {% endif %}
  	{% if registration.agreecheckbox %}
          	<li class="breadcrumb-item"><a href="{% url 'camp:final' registration.id %}">Final Payment</a></li>
          {% endif %}
	{% if not registration.id %}
          <li class="breadcrumb-item"><a href="{% url 'camp:create'%}">New Camp Registration</a></li>
          {% endif %}

        </ul>
   </div>
   {%endif%}


                {% if 'camp:final' in request.resolver_match.view_name %}
		{% endif %}

camp/templates/camp/confirm_registration.html
{% include "camp/header.html" %}
{% include "camp/bootstrap-overrides.html" %}

<style>
.change-message {
    display: none;
}
.asteriskField { display: none; }

</style>

<div class="container-fluid" style="background-color:#e6e6e6">
	<div class="container bg-white border border-secondary">
		{% if registration.registration_source == 1 %}
			{% include "membership/tifdheader.html" %}
		{% else %}
			{% include "camp/tifdheader.html" %}
		{%endif%}
         {% if registration.id %}
                {% if "confirmed" in registration.status.status %}
                        {% include "camp/alreadypaid.html" %}
                {%endif%}
         {%endif%}

		{% include "camp/breadcrumbs.html" %}

	<!--------------shopping cart start ------>

	<div class="row">
    <!--
		<div class="col-sm-5">
			{% include "camp/shopping_cart_table.html" %}
		</div>
    -->

	<!----------------------end shopping cart -->

    <!-- <div class="col-sm-6"> -->
    <div class="col">
		<!-- <p class="h5 text-black p-2">Registration Status: <b>{{registration.status.status}}</b> </p> -->
		<!--even out the columns -->
		<form id="donationform" action={% url 'camp:donaterebate' registration.id %} method=POST>
		<div class="row">
			<div class="donationform w-100 border m-3">
                <p class="table-primary"><b>TIFD donation form</b></p>

                <p class="m-3"> <!-- DONATION TEXT -->
                Good news! Donating to support TIFD has been streamlined into one easy step! As always, TIFD uses your donations to help us present Texas Camp, offer Bobbi Gillotti camp scholarships, present live
folk music, maintain our portable dance floor, and much more. Please give generously, and THANK YOU FOR YOUR SUPPORT! 
                <br><br>
Remember: TIFD is a 501(c)(3) educational organization, and all donations to TIFD are tax deductible!
                </p>
					<table class="table-sm">
					{%csrf_token%}
                    <!--
					<tr>
					    <td>{{ donationform.donation_chuck.label }} <a href="{% url 'camp:help' %}chuck" title="{% include "camp/help-chuck.html" %}">(?)</a>
						<td>{{ donationform.donation_chuck }}
					</tr>
					<tr>
					    <td>{{ donationform.donation_bobbi_gillotti.label }} <a href="{% url 'camp:help' %}bg" title="{% include "camp/help-bg.html" %}">(?)</a>
						<td>{{ donationform.donation_bobbi_gillotti }}
					</tr>
					<tr><td colspan=2> 
					<tr>
						<td>{{ donationform.donation_floor_fund.label }} <a href="{% url 'camp:help' %}ff" title="{% include "camp/help-ff.html" %}">(?)</a>
						<td>{{ donationform.donation_floor_fund }}
					</tr>
					<tr>
						<td>{{ donationform.donation_live_music.label }} <a href="{% url 'camp:help' %}lm" title="{% include "camp/help-lm.html" %}">(?)</a>
						<td>{{ donationform.donation_live_music }}
					</tr>
                    -->
					<tr>
						<td>{{ donationform.donation_tifd.label }} <a class="d-none" href="{% url 'camp:help' %}tifd" title="{% include "camp/help-tifd.html" %}">(?)</a>
						<td>{{ donationform.donation_tifd }}
					</tr>
					</table>
			</div>
		
        </div>

		{% if registration.registration_source == 0 %}
		<!-- SHOW THE FOLLOWING DIVS ONLY FOR CAMP REGISTRATIONS -->

		<div class=row>
			<div class="safetyform w-100 m-3 border">
				<p class="bg-warning text-black font-weight-bold " ><b>Safety agreement</b></p>
                    <div class="p-1">
				        {{safety_agreement|safe}}
						{{safetypolicyform.management_form}}
						{%csrf_token%}
						<b> <div id="agree_container"> {{safetypolicyform}} </div> </b>
                    </div>
			</div>
		</div>
		<div class=row>
			<div class="rebateform w-100 m-3 border">
				<p class="bg-info text-black font-weight-bold "><b>Optional TIFD membership dues rebate</b></p>
				<p>All adult camper registrations include a mandatory $15 fee for membership to TIFD.<br><br>
                If you are a lifetime TIFD member or have already pre-paid your dues for {{ nextyear }}, then use the following form to discount your membership fee.
                <a href="{% url 'camp:check_membership' %}">Click here</a> to check your membership status.  Memberships expire on Thanksgiving day unless renewed.
                
				<div id="rebatebox" class="rebatebox" style="display:one;">

						{%csrf_token%}
						{{rebateform.management_form }}
						{{rebateform}}
						<!--
						<div align=right>
					<button align=left type="submit" id="donatebutton" class="text-white rounded button bg-primary p-1 m-1">Save Rebate</button>
						</div>
						-->
				</div>
			</div>
		</div>
		<div class=row>
			<div class="rebateform w-100 m-3 border">
				<p class="bg-warning text-black font-weight-bold "><b>Favorite dance request form</b></p>
                Use the following link to vote on your favorite dances to be played during the parties!<br>
                <a target="blank" href="https://dancevotes.online/texas-camp-survey">https://dancevotes.online/texas-camp-survey</a>
            </div>
        </div>
		<div class=row>
			<div class="campernotesform w-100 m-3">
				<div id="rebatebox" class="rebatebox" style="display:one;">

						{%csrf_token%}
						{{campernotesform.management_form }}
						{{campernotesform}}
				</div>
			</div>
		</div>

		{%endif%}
		<!-- SHOW THE ABOVE DIVS ONLY FOR CAMP REGISTRATIONS -->

		<div class=row>
			<div class="finalreview w-100 m-3">
				Almost done...
				Continue on to <button type="submit" onclick="agree_checkbox()" id="finalreview" value="yes" name="finalreview" class="text-white rounded button bg-primary p-1 m-1">Final review and payment</button>
			</div>
		</div>
	</div>
</div>
</div>
	        {%include "camp/tifdfooter.html" %}
</div>
</div>
	</form>

	<script>

	$('#id_rebate').on('change', function() {
		//$('#donationform').submit();
        });

	var $form = $('#donationform'),
    	origForm = $form.serialize();


	//If the donation form is changed, alter the color of the button and 
	// provide a warning when user submits the paypal form

	$('form :input').on('change input', function() {
            $('.change-message').toggle($form.serialize() !== origForm);
        });



	//if ($form.serialize() !== origForm){
	//    $("#donatebutton").addClass("bg-primary text-white");
	//    $("#donatebutton").removeClass("bg-white");
//
//	}
//		else { 
//			$("#donatebutton").removeClass("bg-primary text-white"); 
//	    		$("#donatebutton").addClass("bg-white");
//		}
//	});
	function agree_checkbox() {
		if ( document.getElementById('id_agreecheckbox').checked == false ) {
			 document.getElementById('agree_container').style.color="red";
			 document.getElementById('id_agreecheckbox').scrollIntoView();
		}
	}

	$("#paypalform").submit(function (e) {
		if ($form.serialize() !== origForm){
			confirm("You have unsaved changes on the donation form! Are you sure you want to continue to paypal?");
		}
	});

	$("#rebatebutton").click(function(){
	  $("#rebatebox").toggle();
	});

	</script>

	<script>

	$(document).ready(function(){
        {% if "confirmed" in registration.status.status %}
        $('#donationform').find('*').prop('disabled',true);
        {% endif %}
	});
	</script>

	<script>
		$(document).ready(function(){
        {% if "confirmed" in registration.status.status %}
        $('#donationform').find('*').prop('disabled',true);
        {% endif %}
});
	</script>


	</body>

camp/templates/camp/delete.html
                                                <a href="#" title="Delete" class="h5 float-right mr-n3 mt-n1 text-dark align-top" value="Delete-{{forloop.counter0}}" id="delete_{{type}}-{{forloop.counter0}}">
                                                    <button type="button" class="m-2 btn btn-danger">Delete</button>
                                                </a>


                     {%if type == 'child' %}
                          <script>
                              console.log("child");
						$( "#delete_{{type}}-{{forloop.counter0}}" ).click(function() {
                          var c=confirm("Are you sure you want to delete this camper?");
                            if ( c == true ) {
								$( "#regform_{{type}}-{{forloop.counter0}}" ).hide();
								//$('#regform_{{type}}-{{forloop.counter0}}').find('input').val('');
								//$('#regform_{{type}}-{{forloop.counter0}}').find('select').val('');
								//fooooo
								$('#regform_{{type}}-{{forloop.counter0}}').find('input').val('');

								//the above input is finding the checkboxes too
								$("#id_registration_from_{{type}}-{{forloop.counter0}}-join_tifd").val("on");
								$("#id_registration_from_{{type}}-{{forloop.counter0}}-join_tifd").prop( "checked", true);


								//$('#regform_{{type}}-{{forloop.counter0}}').find('checkbox').val('True');
								$('#id_registration_from_{{type}}-{{forloop.counter0}}-membership_years').val(1);

                                $('#regform_{{type}}-{{forloop.counter0}}').find('#registration_from_child-{{forloop.counter0}}-registration_type').val(11);  //child registration type select
                                $('#regform_{{type}}-{{forloop.counter0}}').find('#id_registration_from_child-{{forloop.counter0}}-t_shirt_type').val(1);  //child shirt type select

                                $('#regform_{{type}}-{{forloop.counter0}}').find('#id_registration_from_adult-{{forloop.counter0}}-custom_registration_discount').val(0);
                                $('#regform_{{type}}-{{forloop.counter0}}').find('#id_registration_from_adult-{{forloop.counter0}}-custom_registration_price').val(0);

								 {% if form.instance.pk %}
								//alert("here");
								window.location.href = "{% url "camp:deletecamper" registration.id %}?delete_{{type}}={{ form.instance.pk }}"
								{% endif %}
								return false;
                            }
							else { 
								return false;
							}

                                                });
                          </script>
                      {%else%}
                                        <script>
                              console.log("adult");
						$( "#delete_{{type}}-{{forloop.counter0}}" ).click(function() {
                          var c=confirm("Are you sure you want to delete this camper?");
                            if ( c == true ) {
								$( "#regform_{{type}}-{{forloop.counter0}}" ).hide();
								//$('#regform_{{type}}-{{forloop.counter0}}').find('input').val('');
								//$('#regform_{{type}}-{{forloop.counter0}}').find('select').val('');
								//fooooo
								$('#regform_{{type}}-{{forloop.counter0}}').find('input').val('');

								//the above input is finding the checkboxes too
								$("#id_registration_from_{{type}}-{{forloop.counter0}}-join_tifd").val("on");
								$("#id_registration_from_{{type}}-{{forloop.counter0}}-join_tifd").prop( "checked", true);


								//$('#regform_{{type}}-{{forloop.counter0}}').find('checkbox').val('True');
								$('#id_registration_from_{{type}}-{{forloop.counter0}}-membership_years').val(1);
								{% if registration_source == 1 %}
								$('#regform_{{type}}-{{forloop.counter0}}').find('select').val('107');
								{% else %}
								$('#regform_{{type}}-{{forloop.counter0}}').find('select').val(1);  //change this
                                $('#regform_{{type}}-{{forloop.counter0}}').find('#registration_type-{{forloop.counter0}}').val(1);  //adult registration type select
								{%endif%}

                                $('#regform_{{type}}-{{forloop.counter0}}').find('#id_registration_from_adult-{{forloop.counter0}}-custom_registration_discount').val(0);
                                $('#regform_{{type}}-{{forloop.counter0}}').find('#id_registration_from_adult-{{forloop.counter0}}-custom_registration_price').val(0);

								 {% if form.instance.pk %}
								//alert("here");
								window.location.href = "{% url "camp:deletecamper" registration.id %}?delete_{{type}}={{ form.instance.pk }}"
								{% endif %}
								return false;
                            }
							else { 
								return false;
							}

                                                });
                                        </script>
                   {%endif%}

camp/templates/camp/final.html
{% include "camp/header.html" %}
{% include "camp/bootstrap-overrides.html" %}

<style>
.change-message {
    display: none;
}

</style>


<div class="container-fluid" style="background-color:#e6e6e6">
        <div class="container bg-white border border-secondary">
		<div class="message p-3 m-3">
			<p class="h3 text-center">All your information has been successfully saved.</p>
			<p>
			Please make a final review of all of your information.  If everything looks correct, click one of the payment buttons below to finish registering. 
			</p>
			<p>
			<!--
			You can still still change your registration by using the  <a class="h6 text-black" href="{% url 'camp:create' %}{{registration.id}}#adult_{{forloop.counter}}">(edit)</a> 
			links below or proceed to payment either by <a href={% url 'camp:check_payment' registration.pk %}>mailing a check</a> or clicking the paypal button.</p>
			<p>We are looking forward to seeing you at camp!</p>
			-->
		</div>

		<!-- <div class="col text-dark p-2 mr-2 text-left">Registration Status: <b>{{registration.status.status}}</b> </div> -->

		{% include "camp/breadcrumbs.html" %}
			<div class="row">
				<div class="col">
                                <div class="text-important"><b>Total due: ${{registration.cart_total|stringformat:".02F"}}</b></div>
				</div>
			</div>
			<div class="row">
				<div class="col">
				Payment options:
				<div class="btn-group list-group-horizontal" id="paypaldiv">
                                    <!--
                                    <a href="{%url 'camp:paypal_payment' registration.pk %}"><img src="https://www.paypalobjects.com/webstatic/en_US/i/buttons/checkout-logo-medium.png"></a> 
                                    <a href="{%url 'camp:paypal_payment' registration.pk %}"><img src="/static/img/checkout-logo-medium.png"></a> 
                                    -->
                                 {{ paypal_form.render }} 
				</div>
				<!--
				-->
				{% if registration.registration_source != 99 %}
                                 <div class="btn-group"> <a href={% url 'camp:check_payment' registration.pk %}><button type="button" class="btn btn-primary p-1 mb-2">Mail a check</button></a> </div>
				 {%endif%}
				</div>
			</div>

				 <hr>
		<div class=row>
                   <div class="col-sm-5">
			{% include "camp/shopping_cart_table.html" %}
		</div>

        <div class="col-sm-6">
			{% include "camp/campers_table.html" %}
	</div>
        {%include "camp/tifdfooter.html" %}


<script>
$(document).ready(function(){

    $('#paypaldiv').click(function(e) {
        $.ajax({url: "{% url 'camp:status' registration.pk %}", data:{"action":"change","status":3},async:false,success: function(result){
        $("#div1").html(result);
        }});
        console.log("sent status change request");
    });
});

</script>


	</body>

camp/templates/camp/help-chuck.html
A donation to TIFD in rememberence of Chuck Roth (Dec 5, 1932 – Aug 24, 2022)

camp/templates/camp/view_registrations.html
{% include "camp/header.html" %}

	<div class="container">
<table class="table table-borderd striped">
	<thead>
		<th>Registration</th>
		<th>Name
	</thead>
	<tbody>
	{% for regid,obj in registrations.items %}
	<tr><td><a href="{% url 'camp:confirm' regid %}">{{ regid}}</a>
		<td>
		{% for field  in obj %}
		{{field.first_name}} {{field.last_name}}<br>
		{% endfor %}
		<td>
		{% for field  in obj %}
		{{field.first_name}} {{field.last_name}}<br>
		{% endfor %}

	{% endfor %}